// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhQBb_U7kkHwWq8_YnqMtCTDJm9IpUpuU',
    appId: '1:1048381519306:web:774fbeafdb0e62a8168b33',
    messagingSenderId: '1048381519306',
    projectId: 'weddit-d0e3b',
    authDomain: 'weddit-d0e3b.firebaseapp.com',
    storageBucket: 'weddit-d0e3b.appspot.com',
    measurementId: 'G-BZNCXFVERE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVmBZN3LZmE0x1D4uKw93evBEWqtgx5C4',
    appId: '1:1048381519306:android:c5742d001875a6e5168b33',
    messagingSenderId: '1048381519306',
    projectId: 'weddit-d0e3b',
    storageBucket: 'weddit-d0e3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqgquq5dB-VIwPT9gAnp7vplyIYN9cue0',
    appId: '1:1048381519306:ios:ff069972398df0a2168b33',
    messagingSenderId: '1048381519306',
    projectId: 'weddit-d0e3b',
    storageBucket: 'weddit-d0e3b.appspot.com',
    iosClientId: '1048381519306-320l36eelkjmki9h2c99j1jjcj5vbcb5.apps.googleusercontent.com',
    iosBundleId: 'com.GR2LEIC04T2.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqgquq5dB-VIwPT9gAnp7vplyIYN9cue0',
    appId: '1:1048381519306:ios:ff069972398df0a2168b33',
    messagingSenderId: '1048381519306',
    projectId: 'weddit-d0e3b',
    storageBucket: 'weddit-d0e3b.appspot.com',
    iosClientId: '1048381519306-320l36eelkjmki9h2c99j1jjcj5vbcb5.apps.googleusercontent.com',
    iosBundleId: 'com.GR2LEIC04T2.app',
  );
}
